name: Hello world
author: Spyros Argalias
description: A simple test action
inputs:
  who-to-greet:
    description: Who to greet
    required: true
    default: Test
outputs:
  time:
    description: The greeting time
runs:
  using: node16
  main: ./dist/index.js
